Поддержка функциональных компонентов
esquonk/vue2pug pull request #1
Opened 2019-09-11 06:56 UTC by Shifu462

про `<template functional>`

2019-11-20 15:37 UTC, esquonk requested changes

2019-11-20 15:37 UTC, esquonk commented on vueconverter/formatters.py
> +                          + ' '.join([f'{x}="{y}"' if y != None else x for x, y in tag.attrs.items()])
+ ' '.join(f'{x}="{y}"' if y is not None else x for x, y in tag.attrs.items())

2019-11-21 10:05 UTC, esquonk approved these changes

2019-11-21 10:05 UTC, merged

2019-11-21 10:14 UTC, Shifu462 commented
👍